development:
  adapter: postgresql
  database: nerdword_dev
  min_messages: warning
  username: root
  host: /tmp

test:
  adapter: postgresql
  database: nerdword_test
  min_messages: warning
  username: root
  host: /tmp
