development:
  adapter: postgresql
  database: nerdword_dev
  min_messages: warning
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  database: nerdword_test
  min_messages: warning
  host: localhost
  username: postgres
  password: password
