#!/usr/bin/env ruby
require File.expand_path('../../config/environment',  __FILE__)
require 'capybara/server'
require 'forwardable'
require 'client'

Capybara.server do |app, port|
  require 'rack/handler/thin'
  Thin::Logging.silent = true
  Rack::Handler::Thin.run(app, :Port => port)
end

server = Capybara::Server.new(Rails.application, 8888)
server.boot

puts "Server booted"

player_1_email = "player-#{SecureRandom.hex(10)}@example.com"
player_2_email = "player-#{SecureRandom.hex(10)}@example.com"
password = "password"


# Create player
player_1_client = Client.new
root_resource = RootResource.load(player_1_client.get("/").body)
user_registration_url = root_resource.links.fetch("user-registration")

player_1_client.post(user_registration_url, { :user => { :email => player_1_email, :password => password } }.to_json)
player_1_client.basic_auth(player_1_email, password)


# Create player
player_2_client = Client.new
root_resource = RootResource.load(player_2_client.get("/").body)
user_registration_url = root_resource.links.fetch("user-registration")

player_2_client.post(user_registration_url, { :user => { :email => player_2_email, :password => password } }.to_json)
player_2_client.basic_auth(player_2_email, password)


# Create the game
root_resource = RootResource.load(player_1_client.get("/").body)
games_link = root_resource.links.fetch("games")
player_1_client.post(games_link, { :players => [player_2_email] }.to_json)


# View the game
root_resource = RootResource.load(player_1_client.get("/").body)
games_link = root_resource.links.fetch("games")
games_resource = GamesResource.load(player_1_client.get(games_link).body)

puts "Player 1 has #{games_resource.games.count} games"
games_resource.games.each do |game|
  puts
  game.users.each do |user|
    puts "* #{user.email}"
  end
  puts
end

# View the game
root_resource = RootResource.load(player_2_client.get("/").body)
games_link = root_resource.links.fetch("games")
games_resource = GamesResource.load(player_2_client.get(games_link).body)

puts "Player 2 has #{games_resource.games.count} games"
games_resource.games.each do |game|
  puts
  game.users.each do |user|
    puts "* #{user.email}"
  end
  puts
end
